package com.mycompany.mvptrabalho.view;

import com.mycompany.mvptrabalho.presenter.HistoricoPrecoPresenter;
import java.util.List;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;

/**
 * Tela de histórico de preços do produto (Figura 5), somente consulta.
 */
public class HistoricoPrecoTela extends javax.swing.JInternalFrame implements HistoricoPrecoView {


    private HistoricoPrecoPresenter presenter;

    public HistoricoPrecoTela() {
        initComponents();
        UtilTela.definirEditavel(txtProduto, false);
        UtilTela.definirEditavel(txtCategoria, false);
        UtilTela.configurarTabela(tblHistorico, 1, 2);
        // Fechar pelo botão ou pelo "X" da janela avisa o Presenter.
        addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(InternalFrameEvent e) {
                if (presenter != null) {
                    presenter.aoFecharTela();
                }
            }
        });
    }

    @Override
    public void setPresenter(HistoricoPrecoPresenter presenter) {
        this.presenter = presenter;
    }

    @Override
    public void exibir() {
        UtilTela.exibirCentralizada(this);
    }

    @Override
    public void fechar() {
        dispose();
    }

    @Override
    public void setProduto(String produto) {
        txtProduto.setText(produto);
    }

    @Override
    public void setCategoria(String categoria) {
        txtCategoria.setText(categoria);
    }

    @Override
    public void exibirHistorico(List<String[]> linhas) {
        UtilTela.preencherTabela(tblHistorico, linhas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProduto = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        scrHistorico = new javax.swing.JScrollPane();
        tblHistorico = new javax.swing.JTable();
        btnFechar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Histórico de Preços do Produto");

        lblProduto.setText("Produto:");

        lblCategoria.setText("Categoria:");

        txtProduto.setEditable(false);

        txtCategoria.setEditable(false);

        tblHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Percentual de lucro (%)", "Preço de venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        scrHistorico.setViewportView(tblHistorico);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblProduto)
                                .addComponent(lblCategoria))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(scrHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                        .addComponent(btnFechar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblProduto)
                        .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoria)
                        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(scrHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnFechar)
                    .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        presenter.aoClicarFechar();
    }//GEN-LAST:event_btnFecharActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JScrollPane scrHistorico;
    private javax.swing.JTable tblHistorico;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtProduto;
    // End of variables declaration//GEN-END:variables
}
